server:
  port: 8761

spring:
  application:
    name: discoveryservice
  cloud:
    config:
      uri: http://localhost:8888
      name: ecommerce

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false